apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-creator-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: deployment-creator
    namespace: default
roleRef:
  kind: Role
  name: deployment-creator-role
  apiGroup: rbac.authorization.k8s.io
# RBAC rules for deployment status service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: status-service-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-service-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: status-service-account
    namespace: default
roleRef:
  kind: Role
  name: status-service-role
  apiGroup: rbac.authorization.k8s.io