apiVersion: v1
kind: ConfigMap
metadata:
  name: component-configs
data:
  cu.yaml: |
    log:
      filename: stdout
      cu_level: info

    cu_cp:
      amf:
        no_core: true
        addr: 127.0.1.100
        bind_addr: 10.244.0.4
        supported_tracking_areas:
          - tac: 7
            plmn_list:
              - plmn: "00101"
                tai_slice_support_list:
                  - sst: 1
      f1ap:
        bind_addr: 10.244.0.4

    expert_execution:
      threads:
        non_rt:
          nof_non_rt_threads: 2