apiVersion: v1
kind: ConfigMap
metadata:
  name: component-configs
data:
  cu.yaml: |
    log:
      filename: stdout
      cu_level: info

    cu_cp:
      amf:
        no_core: true
        addr: 127.0.1.100
        bind_addr: __MY_IP__
        supported_tracking_areas:
          - tac: 7
            plmn_list:
              - plmn: "00101"
                tai_slice_support_list:
                  - sst: 1
      f1ap:
        bind_addr: __MY_IP__

    expert_execution:
      threads:
        non_rt:
          nof_non_rt_threads: 2
  du.yaml: |
    log:
      filename: stdout

    f1ap:
      cu_cp_addr: __CU_IP__
      bind_addr: __MY_IP__

    nru:
      bind_addr: __MY_IP__

    ru_ofh:
      t1a_max_cp_dl: 470
      t1a_min_cp_dl: 258
      t1a_max_cp_ul: 500
      t1a_min_cp_ul: 285
      t1a_max_up: 196
      t1a_min_up: 50
      is_prach_cp_enabled: true
      is_dl_broadcast_enabled: false
      ignore_ecpri_payload_size: true
      compr_method_ul: bfp
      compr_bitwidth_ul: 9
      compr_method_dl: bfp
      compr_bitwidth_dl: 9
      compr_method_prach: bfp
      compr_bitwidth_prach: 9
      enable_ul_static_compr_hdr: true
      enable_dl_static_compr_hdr: true
      iq_scaling: 1.0
      cells:
      - network_interface: __MY_IF__
        ru_mac_addr: 52:54:00:ca:b9:b4
        du_mac_addr: __MY_MAC__
        prach_port_id: [4]
        dl_port_id: [0, 1, 2, 3]
        ul_port_id: [0]

    cell_cfg:
      dl_arfcn: 625000
      band: 78
      channel_bandwidth_MHz: 100
      common_scs: 30
      plmn: "00101"
      tac: 7
      pci: 1
      prach:
        prach_config_index: 159
        prach_root_sequence_index: 1
        zero_correlation_zone: 0
        prach_frequency_start: 12
      nof_antennas_dl: 4
      nof_antennas_ul: 1
      tdd_ul_dl_cfg:
        nof_dl_symbols: 7
        nof_dl_slots: 7
        nof_ul_slots: 2

    test_mode:
      test_ue:
        rnti: 0x1
        ri: 4