apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-cu
  template:
    metadata:
      labels:
        app: srsran-cu
    spec:
      initContainers:
      - name: init-cu
        image: busybox
        command: ['sh', '/scripts/network-info-cu.sh']
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          runAsUser: 0
        volumeMounts:
        - name: config-template-volume
          mountPath: /config-template
        - name: config-volume
          mountPath: /config
        - name: script-volume
          mountPath: /scripts
        - name: shared
          mountPath: /shared
      containers:
      - name: cu
        image: ekelhala/srsran-container
        command: ["srscu"]
        args: ["-c", "/config/cu.yaml"]
        volumeMounts:
          - name: config-volume
            mountPath: /config
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "5Gi"
          limits:
            memory: "7Gi"
      volumes:
      - name: config-template-volume
        configMap:
          name: component-configs
      - name: config-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: scripts-config
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-du
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-du
  template:
    metadata:
      labels:
        app: srsran-du
    spec:
      initContainers:
        - name: init-du
          image: busybox
          command: ['sh', '/scripts/network-info-du.sh']
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 0
          volumeMounts:
          - name: config-template-volume
            mountPath: /config-template
          - name: config-volume
            mountPath: /config
          - name: script-volume
            mountPath: /scripts
          - name: shared
            mountPath: /shared
        - name: init-ru
          image: busybox
          command: ['sh', '/scripts/network-info-ru.sh']
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 0
          volumeMounts:
          - name: config-template-volume
            mountPath: /config-template
          - name: config-volume
            mountPath: /config
          - name: script-volume
            mountPath: /scripts
          - name: shared
            mountPath: /shared
      containers:
        - name: du
          image: ekelhala/srsran-container
          command: ['sh', '-c', 'cat /config/du.yaml && srsdu -c /config/du.yaml']
          volumeMounts:
            - name: config-volume
              mountPath: /config
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 0
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "5Gi"
        - name: ru
          image: ekelhala/srsran-container
          command: ['sh', '-c', 'cat /config/ru.yaml && ru_emulator -c /config/ru.yaml']
          volumeMounts:
            - name: config-volume
              mountPath: /config
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
            runAsUser: 0
          resources:
            requests:
              memory: "5Gi"
            limits:
              memory: "6Gi"
      volumes:
      - name: config-template-volume
        configMap:
          name: component-configs
      - name: config-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: scripts-config
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc
