apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran
  template:
    metadata:
      labels:
        app: srsran
    spec:
      containers:
      - name: cu
        image: ekelhala/srsran-container
        command: ['sh', '-c', 'sed "s/__MY_IP__/$POD_IP/" /config/cu.yaml > /config/cu.yaml', '&&', 'srscu']
        args: ["-c", "/config/cu.yaml"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: "/config"
      volumes:
      - name: config-volume
        configMap:
          name: component-configs
          items:
          - key: "cu.yaml"
            path: "cu.yaml"