apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran
  template:
    metadata:
      labels:
        app: srsran
    spec:
      containers:
      - name: cu
        image: ekelhala/srsran-container
        command: ["srsdu"]
        args: ["-c", "/config/cu.yaml"]
        volumeMounts:
          - name: config_volume
            mountPath: "/config"
            subPath: cu.yaml
      volumes:
      - name: config_volume
        configMap:
          name: component-configs
          items:
          - key: "cu.yaml"
            path: "cu.yaml"