apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran
  template:
    metadata:
      labels:
        app: srsran
    spec:
      initContainers:
      - name: init-cu
        image: busybox
        command: ['sh', '/scripts/network-info-cu.sh']
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          runAsUser: 0
        volumeMounts:
        - name: config-template-volume
          mountPath: /config-template
        - name: config-volume
          mountPath: /config
        - name: script-volume
          mountPath: /scripts
      - name: init-du
        image: busybox
        command: ['sh', '/scripts/network-info-du.sh']
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          runAsUser: 0
        volumeMounts:
        - name: config-template-volume
          mountPath: /config-template
        - name: config-volume
          mountPath: /config
        - name: script-volume
          mountPath: /scripts
      containers:
      - name: cu
        image: ekelhala/srsran-container
        command: ["srscu"]
        args: ["-c", "/config/cu.yaml"]
        volumeMounts:
          - name: config-volume
            mountPath: /config
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "5Gi"
          limits:
            memory: "7Gi"
      - name: du
        image: ekelhala/srsran-container
        command: ['sh', '-c', 'cat /config/du.yaml && srsdu -c /config/du.yaml']
        volumeMounts:
          - name: config-volume
            mountPath: /config
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
          runAsUser: 0
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "5Gi"
      volumes:
      - name: config-template-volume
        configMap:
          name: component-configs
      - name: config-volume
        emptyDir: {}
      - name: script-volume
        configMap:
           name: scripts-config