apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran
  template:
    metadata:
      labels:
        app: srsran
    spec:
      initContainers:
      - name: init-cu
        image: busybox
        command: ['sh', '-c', 'mkdir -p /config && sed "s/__MY_IP__/$POD_IP/" /config-template/cu.yaml > /config/cu.yaml']
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-template-volume
          mountPath: /config-template
        - name: config-volume
          mountPath: /config
      containers:
      - name: cu
        image: ekelhala/srsran-container
        command: ['sh', '-c', 'cat /config/cu.yaml && srscu']
        args: ["-c", "/config/cu.yaml"]
        volumeMounts:
          - name: config-volume
            mountPath: /config
        securityContext:
          privileged: true
      volumes:
      - name: config-template-volume
        configMap:
          name: component-configs
      - name: config-volume
        emptyDir: {}