apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-config
data:
  network-info.sh: |
    #!/bin/sh
    INTERFACE_NAME=$(ip -o link show | awk -F': ' '{print $2}' | head -n 1)
    IP_ADDRESS=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
    MAC_ADDRESS=$(cat /sys/class/net/eth0/address)
    sed -i "s/__MY_IF__/${INTERFACE_NAME}/" /mnt/config/config.yaml
    sed -i "s/__MY_IP__/${IP_ADDRESS}/" /config-template/du.yaml
    sed -i "s/__MY_MAC__/${MAC_ADDRESS}/" /config-template/du.yaml
