apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-config
data:
  network-info-du.sh: |
    #!/bin/sh
    INTERFACE_NAME=$(ip -o link show | awk -F': ' '{print $2}' | head -n 1)
    IP_ADDRESS=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
    MAC_ADDRESS=$(cat /sys/class/net/eth0/address)
    CU_IP_ADDRESS=$(cat /shared/cu_ip.txt)
    sed -e "s/__MY_IF__/${INTERFACE_NAME}/" \
           -e "s/__MY_IP__/${IP_ADDRESS}/" \
           -e "s/__CU_IP__/${CU_IP_ADDRESS}/" \
           -e "s/__MY_MAC__/${MAC_ADDRESS}/" /config-template/du.yaml > /config/du.yaml \
    && echo $MAC_ADDRESS > /shared/du_mac.txt
  network-info-cu.sh: |
    #!/bin/sh
    INTERFACE_NAME=$(ip -o link show | awk -F': ' '{print $2}' | head -n 1)
    IP_ADDRESS=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
    MAC_ADDRESS=$(cat /sys/class/net/eth0/address)
    sed -e "s/__MY_IP__/${IP_ADDRESS}/" /config-template/cu.yaml > /config/cu.yaml
  network-info-ru.sh: |
     #!/bin/sh
     INTERFACE_NAME=$(ip -o link show | awk -F': ' '{print $2}' | head -n 1)
     DU_MAC_ADDRESS=$(cat /shared/du_mac.txt)
     sed -e "s/__MY_IF__/${INTERFACE_NAME}/" \
          -e "s/__DU_MAC__/${DU_MAC_ADDRESS}/" \
          /config-template/ru.yaml > /config/ru.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'worker'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: worker-service
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9000"
            action: keep
      - job_name: 'api-server'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: api-server-service
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "80"
            action: keep
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/monitoring/
    serve_from_sub_path = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://10.106.53.165:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"