apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-service-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-service-stack
  template:
    metadata:
      labels:
        app: srsran-service-stack
    spec:
      serviceAccountName: deployment-creator
      containers:
        - name: rabbitmq-broker
          image: rabbitmq
        - name: worker
          image: ekelhala/srsran-worker
        - name: api-server
          image: ekelhala/srsran-api-server
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: srsran-api-server-service
spec:
  selector:
    app: srsran-service-stack
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-creator-role
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: deployment-creator
    namespace: default
roleRef:
  kind: Role
  name: deployment-creator-role
  apiGroup: rbac.authorization.k8s.io
