apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-service-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srsran-service-stack
  template:
    metadata:
      labels:
        app: srsran-service-stack
    spec:
      serviceAccountName: deployment-creator
      containers:
        - name: rabbitmq-broker
          image: rabbitmq
        - name: worker
          image: ekelhala/srsran-worker
          ports:
            - containerPort: 9000
        - name: api-server
          image: ekelhala/srsran-api-server
          ports:
            - containerPort: 80
        - name: mongo
          image: mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: mongodb-storage
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: db-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: srsran-api-server-service
spec:
  selector:
    app: srsran-service-stack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: monitoring
spec:
  selector:
    app: srsran-service-stack
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  clusterIP: 10.105.0.20
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: monitoring
spec:
  selector:
    app: srsran-service-stack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.105.0.21